### ISSUE TITLE
Adjusting "Length above ground" by arrows causes crash

### ISSUE THREAD

**Issue by chrshffmn** [NHERI-SimCenter/QtPile#31]
On Mac, in "Site Configuration” group, "Length above ground" field: Increase or decrease value a few times using up and down arrows causes a crash. Error messages in output look like:
StaticAnalysis::analyze() - the Algorithm failed at iteration: 19 with domain at load factor 1
ERROR:  52  nodes generated but  57 expected 

WARNING Domain::addElement - In element 166
 no Node 167 exists in the domain
WARNING Domain::addElement - In element 167
 no Node 167 exists in the domain
WARNING Domain::addElement - In element 168
 no Node 168 exists in the domain
WARNING Domain::addElement - In element 169
 no Node 169 exists in the domain
WARNING Domain::addElement - In element 170
 no Node 170 exists in the domain
WARNING NodalLoad::applyLoad() - No associated Node node  for NodalLoad Nodal Load: 171 load : 250 0 0 0 0 0 
... 
The program has unexpectedly finished.

**Comment by pmackenz** [comment]
I believe I fixed this bug.  It was part of a series of bugs that could arise by setting some parameters to zero without the proper handling in the code.  Please try again and let me know if I really fixed your issue.
Thanks!

**Comment by chrshffmn** [comment]
I've tested this after updating my local repo, and the crash did not reappear.  Looks good to me! I will do some more testing on this version. Thanks,
Chris
