### ISSUE TITLE
MS - Windows QtPile version

### ISSUE THREAD

**Issue by parduino** [NHERI-SimCenter/QtPile#53]

**Comment by parduino** [comment]
compiles and starts well.
Fonts need to be checked
Size of window must be check such that it accommodates the user screen

**Comment by pmackenz** [comment]
Font issue resolved. There were two kind of issues:

1. Text in the HTML viewer was transferred from word/office document using copy/paste and, thus, contained lots and lots of useless font information.  This messed up the "Hints" section in mainwindow and two of the dialogues.
2. there was a property->font section in mainwindow.ui that set the font to 15 pt.  There was no location in Qt Designer accessing that field, so I guess that was a leftover from modifications (a bug in Designer or user hacking the ui file with an editor).
